FROM almalinux:8
LABEL AUTHOR="Hari" \
      INSTRUCTION="Label" \
      OS="Almalinux" 

## \ Slash should be given if are specifing mutliple LABELS
## LABEL Instrction adds extra metadata to an image.
## We can filter the image by using the lables.
## docker images --filter label=AUTHOR=Hari

      
      


