FROM almalinux:8
RUN yum install nginx -y
EXPOSE 80/tcp
CMD ["nginx","-g","daemon off;"]

##EXPOSE will jsut gives the information of the port the container is running.
## docker inspect <Image_ID> it gives the information of the image there also we can see the port.


